// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// Show 5 EMA, 20 EMA, 50 SMA, 100 SMA and 200 SMA
// By ezPappi https://twitter.com/ezPappi
// @version 0.1

study(title="5EMA-20EMA-50SMA-100SMA-200SMA", shorttitle="ema5_ema10_sma50_sma100_sma200", overlay=true)

// 1.MA50 must be at top
// 2.MA100 must be in the middle
// 3.MA200 must be at the bottom

length1=input(5, minval=1,title="EMA 5 Length")
length2=input(20, minval=1,title="EMA 20 Length")
length3=input(50, minval=1,title="SMA 50 Length")
length4=input(100, minval=1,title="SMA 100 Length")
length5=input(200,minval=1,title="SMA 200 Length")

ema1=ema(close,length1)
ema2=ema(close,length2)
sma3=sma(close,length3)
sma4=sma(close,length4)
sma5=sma(close,length5)

plot(ema1,color=aqua ,linewidth=2, title="5EMA")
plot(ema2,color=lime ,linewidth=2, title="20EMA")
plot(sma3,color=blue ,linewidth=2, title="50SMA")
plot(sma4,color=red ,linewidth=2, title="100SMA")
plot(sma5,color=green,linewidth=2, title="200SMA")

